In [2]:
import tensorflow as tf

def get_frozen_graph(graph_file):
    """Read Frozen Graph file from disk."""
    with tf.gfile.FastGFile(graph_file, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    return graph_def

# The TensorRT inference graph file downloaded from Colab or your local machine.
pb_fname = "./models/trt_model/trt_graph.pb"

print("reading graph")
trt_graph = get_frozen_graph(pb_fname)
print("Done reading graph")

input_names = ['image_tensor']



reading graph
Instructions for updating:
Use tf.gfile.GFile.
Done reading graph


In [3]:
# Create session and load graph
tf_config = tf.ConfigProto()
# config = tf.ConfigProto(
#         device_count = {'GPU': 0}
#     )
# tf_sess = tf.Session(config=config)
tf_config.gpu_options.allow_growth = True
tf_sess = tf.Session(config=tf_config)
tf.import_graph_def(trt_graph, name='')

tf_input = tf_sess.graph.get_tensor_by_name(input_names[0] + ':0')
tf_scores = tf_sess.graph.get_tensor_by_name('detection_scores:0')
tf_boxes = tf_sess.graph.get_tensor_by_name('detection_boxes:0')
tf_classes = tf_sess.graph.get_tensor_by_name('detection_classes:0')
tf_num_detections = tf_sess.graph.get_tensor_by_name('num_detections:0')



In [4]:
import cv2
cap = cv2.VideoCapture(0)

In [33]:
while True:
    return_key, image = cap.read()
    image = cv2.resize(image, (300, 300))
    scores, boxes, classes, num_detections = tf_sess.run([tf_scores, tf_boxes, tf_classes, tf_num_detections], feed_dict={
    tf_input: image[None, ...]
    })

    boxes = boxes[0]  # index by 0 to remove batch dimension
    scores = scores[0]
    classes = classes[0]
    num_detections = int(num_detections[0])
    print(boxes[0])
    print(scores[0])
#     for i in range (0, num_detections):
    if(scores[0] > 0.5):
        b1 = int(boxes[0][0] * 299)
        b2 = int(boxes[0][1] * 299)
        b3 = int(boxes[0][2] * 299)
        b4 = int(boxes[0][3] * 299)
        print(b2)
        image[b1, b3] = [255, 255, 0]
        image[b3, b2] = [255, 255, 0]
        image[b3, b4] = [255, 255, 0]
        image[b1, b4] = [255, 255, 0]
#         image[boxes[0][1],boxes[0][0]] = 255
#         image[boxes[0][1],boxes[0][0]] = 255
#         image[boxes[0][3],boxes[0][2]] = 255

[0.         0.3423909  0.9868634  0.98788154]
0.99869007
102
[0.         0.35885316 0.9896606  0.9986368 ]
0.99921215
107
[0.00196961 0.35101464 0.9911933  0.97396016]
0.99923795
104
[0.00536358 0.3245984  0.98633873 0.9455147 ]
0.9974009
97
[0.00531    0.31975645 0.98954743 0.9521592 ]
0.9986773
95
[4.1478872e-04 3.1759983e-01 9.9338883e-01 9.8209614e-01]
0.99889225
94
[0.         0.32696036 0.9912096  0.9892602 ]
0.99944764
97
[0.         0.34771487 0.9891728  1.        ]
0.9993679
103
[0.         0.36786735 0.98870474 1.        ]
0.999281
109
[0.         0.37853277 0.99255395 1.        ]
0.99961424
113
[0.         0.33524236 0.9908611  0.99761975]
0.999569
100
[0.00413367 0.27843466 0.9956782  0.9913074 ]
0.99982977
83
[0.        0.2134963 0.994696  0.9844632]
0.9997124
63
[0.         0.14893979 0.9915395  1.        ]
0.9999869
44
[0.00192231 0.14374903 0.98880976 1.        ]
0.9999886
42
[0.         0.18928102 1.         0.99084854]
0.999966
56
[0.         0.24096382 0.99767774 0.9

KeyboardInterrupt: 

In [14]:
cap.release()